# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7d4f9ff0711296af5b09137383518d422f58b2907d09620e5b2fa8a64102df537d1f06928c542509b1d73db8e9a9e7f463a67a22f71689b9d7ac58a6bc7668

test:
  secret_key_base: 72a9b612ff89104b382518611d49d6ed92dfc950071f8ea64c4aa98b2d6f91e9caa7ca90fc2857294c7666487d39ec998008cab13914cb9145dda093bf4c5dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
